### ISSUE TITLE
Cannot build for Windows

### ISSUE THREAD

**Issue by indarkness** [jjo/openvpn-ipv6#1]
The lzo and openssl headers could not be included.
I tried to build with domake-win (mingw).

**Comment by jjo** [comment]
Hi there,

I've uploaded v2.2-RC2-ipv6-0.4.16 which fixed mingw32 build under Linux for me,
it was mainly a missing ws2tcpip.h for some base types.
I've also uploaded a openvpn.exe build (gpg-signed exe, no installer)

I'm closing this issue for now, feel free to reopen if needed.
Cheers --J
