### ISSUE TITLE
LZO libraries unusuable when compiling with MinGW

### ISSUE THREAD

**Issue by ghost** [jjo/openvpn-ipv6#2]
Hi! I managed to build openvpn _without_ ipv6 patch, but after I patched the source LZO "breaks", like this:

checking for working memcmp... no
res_init UNDEFINED
configure: checking for working epoll implementation...
checking for epoll_create... no
configure: checking for struct sockaddr_in6 for IPv6 support...
checking for struct sockaddr_in6... no
LoadLibrary DEFINED
configure: checking for LZO Library and Header files...
checking lzo/lzo1x.h usability... no
checking lzo/lzo1x.h presence... yes
configure: WARNING: lzo/lzo1x.h: present but cannot be compiled
configure: WARNING: lzo/lzo1x.h:     check for missing prerequisite headers?
configure: WARNING: lzo/lzo1x.h: see the Autoconf documentation
configure: WARNING: lzo/lzo1x.h:     section "Present But Cannot Be Compiled"
configure: WARNING: lzo/lzo1x.h: proceeding with the compiler's result
configure: WARNING:     ## -------------------------------------------------- ##
configure: WARNING:     ## Report this to openvpn-users@lists.sourceforge.net ##
configure: WARNING:     ## -------------------------------------------------- ##
checking for lzo/lzo1x.h... no
checking lzo1x.h usability... no
checking lzo1x.h presence... no
checking for lzo1x.h... no
LZO headers were not found
LZO library available from http://www.oberhumer.com/opensource/lzo/
configure: error: Or try ./configure --disable-lzo
make: **\* No targets specified and no makefile found.  Stop.
cp: cannot stat `windest/sbin/openvpn.exe': No such file or directory

OpenVPN 2.1.3 source
Patch: what I've found here

I tried 2 patches neither it worked, I'm still trying hard, I compile LZO or something
Oh yes and I used these prebuilt binaries: http://openvpn.net/prebuilt/

Any help would be appriciated!
Thanks, 

Gorkhaan

**Comment by ghost** [comment]
If I add "--disable-lzo" to configure OpenSSL will break too:

configure: checking for OpenSSL Crypto Library and Header files...
checking openssl/evp.h usability... no
checking openssl/evp.h presence... yes
configure: WARNING: openssl/evp.h: present but cannot be compiled
configure: WARNING: openssl/evp.h:     check for missing prerequisite headers?
configure: WARNING: openssl/evp.h: see the Autoconf documentation
configure: WARNING: openssl/evp.h:     section "Present But Cannot Be Compiled"
configure: WARNING: openssl/evp.h: proceeding with the compiler's result
configure: WARNING:     ## -------------------------------------------------- ##
configure: WARNING:     ## Report this to openvpn-users@lists.sourceforge.net ##
configure: WARNING:     ## -------------------------------------------------- ##

checking for openssl/evp.h... no
configure: error: OpenSSL Crypto headers not found.
make: **\* No targets specified and no makefile found.  Stop.

**Comment by jjo** [comment]
Hi Gorkhaan,

Thanks a lot for the detailed report.

I've uploaded v2.2-RC2-ipv6-0.4.16 which fixed mingw32 build under Linux for me,
it was mainly a missing ws2tcpip.h for some base types.
I've also uploaded a openvpn.exe build (gpg-signed exe, no installer)

Cheers --J

**Comment by ghost** [comment]
Hi!

Thanks for your fast patch and reply! I will try compile it again tomorrow (just for fun. ^^ )!

Thanks,

G.
